name: widgets_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.4.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 24
  adaptative_icon_background: "#FFFFFF"
  adaptative_icon_foreground: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
